[[main]]
  name = "News"
  identifier = "news"
  pre = '<i class="fa fa-fw fa-newspaper"></i>'
  weight = 2
#url = "https://example.org"

#[[main]]
#  name = "Tutorials"
#  identifier = "tutorials"

[[main]]
  name = "About"
  identifier = "about"
  pre = '<i class="fa fa-fw fa-user"></i>'

[[main]]
  parent = "about"
  name = "Github"
  url = "https://github.com/loongarch64/"
  pre = '<i class="fab fa-fw fa-github"></i>'
